use std::{env, fs, path::PathBuf};

fn main() {
    embed_addon();
    tauri_build::build()
}

/// Writes the source of `BUNDLED_ADDON`: the addon this build ships, file by file.
///
/// The app and the addon are two halves of one pipeline, so the binary carries its own copy
/// rather than fetching one — whatever the app installs is then necessarily the addon that
/// was in the tree when the app was compiled.
///
/// The .toc decides what goes in. It is the addon's own manifest, the list the game client
/// itself loads, so anything else under `apps/addon` — the busted specs above all — is not
/// part of the addon and has no business in either the binary or the game folder.
fn embed_addon() {
    let addon = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../../addon")
        .canonicalize()
        .expect("apps/addon should sit two levels above src-tauri");
    let toc = addon.join("chronie.toc");
    println!("cargo:rerun-if-changed={}", toc.display());

    let manifest = fs::read_to_string(&toc).expect("the addon should have a chronie.toc");
    let mut entries = vec![entry(&toc, "chronie.toc")];
    for line in manifest.lines() {
        let listed = line.trim();
        if listed.is_empty() || listed.starts_with('#') {
            continue;
        }
        // Real .toc files address files with backslashes; this one uses forward slashes.
        // Accept either, and refuse anything that would escape the addon folder.
        let relative = listed.replace('\\', "/");
        assert!(
            !relative.starts_with('/') && !relative.split('/').any(|part| part == ".."),
            "chronie.toc lists a path outside the addon: {listed}"
        );
        let source = addon.join(&relative);
        println!("cargo:rerun-if-changed={}", source.display());
        assert!(source.is_file(), "chronie.toc lists a missing file: {listed}");
        entries.push(entry(&source, &relative));
    }

    let generated = format!(
        "/// Every file the shipped addon is made of, keyed by its path inside the addon\n\
         /// folder. Generated by build.rs from apps/addon/chronie.toc.\n\
         static BUNDLED_ADDON: &[(&str, &[u8])] = &[\n{}];\n",
        entries.concat()
    );
    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("bundled_addon.rs");
    fs::write(&out, generated).expect("the generated addon manifest should be writable");
}

/// One `(path, bytes)` row. Both literals go through `{:?}`, which escapes the backslashes a
/// Windows path arrives with instead of letting them start an escape sequence.
fn entry(source: &PathBuf, relative: &str) -> String {
    format!(
        "    ({relative:?}, include_bytes!({:?})),\n",
        source.to_string_lossy()
    )
}
