// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * What the game says about the achievements a window is showing.
 *
 * The dashboard already carries the ids, because the addon recorded them at the moment they
 * were earned; everything a reader recognises an achievement by is in the game's own tables
 * and is looked up here. Asked for after the segment is drawn, for the same reason the
 * icons are: a list of achievements is worth reading while the tables that describe them
 * are still being opened.
 */
async achievementDetails(ids: number[]) : Promise<Result<AchievementDetailsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("achievement_details", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The four ways a user can correct the app's guess about what a segment was.
 *
 * Each one returns the whole dashboard rather than an acknowledgement, so the window
 * repaints from stored state instead of from what the frontend hoped the write did.
 */
async addActivity(segmentId: number, kind: string, metadata: Partial<{ [key in string]: ActivityValue }>) : Promise<Result<DashboardPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_activity", { segmentId, kind, metadata }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One capture at the size it was taken, which is what opening a picture asks for.
 */
async captureImage(captureId: number) : Promise<Result<CaptureImagePayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_image", { captureId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The pictures a grid of captures needs, asked for once the rows are drawn.
 *
 * Async, and not for the bridge's sake: the first look at an evening's captures decodes and
 * re-encodes a screenshot apiece, which is tens of milliseconds each and would hold the main
 * thread for the length of the grid. Every one after that is a file read, because the
 * thumbnails are kept beside the images they were made from.
 */
async captureThumbnails(captureIds: number[]) : Promise<Result<CaptureThumbnailsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_thumbnails", { captureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the reader may be asked about her, what they have answered so far, and who they play.
 *
 * The first two halves at once because neither is any use alone: a list of swatches with nothing
 * marked is a form that cannot say what it is showing, and a set of ids with no names behind them
 * is what the settings file already holds. See [`customization::questions`] — a question is read
 * out of the installed game, so a patch that adds a hairstyle adds it here with no code.
 *
 * The third is the roster, and it travels with them for the same reason: it is a shortcut *into*
 * this form — pick a character and every control below fills in — so a window that had to ask for
 * it separately would be making two round trips to draw one panel. It is re-read whenever the
 * body changes, which costs a query against a table with one row per character.
 */
async characterLook() : Promise<Result<CharacterLookPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("character_look") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The character an appearance is worn on, bare, as a `.glb` in a data URL.
 *
 * One fixed model for the whole app — a Human Female, because gear is authored to look right
 * on human proportions — so this is asked for once and shown for every set opened after.
 *
 * Which Human Female is the reader's, out of [`character_look`]. It is read here rather than
 * sent by the window because it is the same answer for every one of the three commands that
 * draw her, and because a window that had to remember to pass it could forget in one of them —
 * which would be a wardrobe of strangers.
 */
async characterModel() : Promise<Result<CharacterModelPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("character_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The same, on a body belonging to somebody the reader actually plays.
 *
 * The one place in the app where the body is not the reader's invented one. Everywhere else a
 * picture is of a person somebody put together out of fifty-one bodies and a select per
 * question, and that is right for a wardrobe: a look is being *chosen* there, and it should be
 * shown on whoever the reader means to wear it. The character view asks a different question —
 * what does this Tauren I play look like in the set she saved — and answering it with the
 * Human Female the transmog screen happens to be set to would be answering somebody else's.
 *
 * **Which is exactly what it used to do.** A character this install cannot recognise fell back
 * to the reader's own body, on the argument that a picture on the wrong body is still a picture
 * of the clothes. That argument belongs to the wardrobe and not to a portrait: on the machine
 * that reported #222 there was no look stored for anybody, so every night elf on the roster was
 * drawn as the Kul Tiran Male the transmog screen happened to be set to, and nothing said so.
 * So the fallback is gone, and what comes back instead says how much of the body is really the
 * character's — see [`character::Likeness`], and `look.rs` for why it is so often so little.
 */
async characterWornSet(character: string, pieces: WornPiece[]) : Promise<Result<CharacterWornSetPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("character_worn_set", { character, pieces }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForAppUpdate() : Promise<Result<AppUpdateResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_app_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Asks the user for the game folder.
 *
 * This has to be `async`. Tauri runs a synchronous command on the main thread, and the
 * folder picker blocks until the user answers it — on the main thread that is the event
 * loop the picker itself needs, so the whole window locks up with the dialog on screen.
 * An async command runs off the main thread, which is what the dialog plugin's own
 * documentation calls for.
 */
async chooseWowPath() : Promise<string | null> {
    return await TAURI_INVOKE("choose_wow_path");
},
async combatLogging() : Promise<Result<Status, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("combat_logging") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The pictures a list of currencies is drawn with, keyed by the currency rather than the file.
 *
 * Keyed by the currency because that is what the caller holds: a balance arrives from the addon
 * as an id, a name and a number, and the FileDataID behind it is a hop this side of the bridge
 * has no way to make and no reason to learn. So the whole errand happens here — the table, then
 * the texture — and the window gets back what it can put in an `<img>`.
 *
 * The textures themselves go through the same cache every other icon does, so a second
 * character holding the same currency costs the table read and nothing else.
 */
async currencyIcons(currencyIds: number[]) : Promise<Result<IconsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("currency_icons", { currencyIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The sets the reader put together on the character themselves.
 *
 * The other thing on the transmog screen that is not read out of the installed game, and the
 * only one of the two that has clothes in it: an outfit assembled out of several sets and the
 * game at large, saved under a name and browsed beside Blizzard's own ever after. Read whole
 * for the reason the marks are — see `collector::custom_sets`.
 */
async customSets() : Promise<Result<CustomSetsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("custom_sets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dashboard() : Promise<Result<DashboardPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dashboard") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteActivity(activityId: number) : Promise<Result<DashboardPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_activity", { activityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCapture(captureId: number) : Promise<Result<DashboardPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_capture", { captureId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCustomSet(id: number) : Promise<Result<CustomSetsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_custom_set", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTransmogTag(kind: MarkSubjectKind, id: number, key: string) : Promise<Result<TransmogMarksPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_transmog_tag", { kind, id, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A page of the wardrobe, every appearance on it worn on a body of its own.
 *
 * The same three numbers per row as [`worn_set`], and a very different question: that one is
 * one body wearing several things, and this is several bodies each wearing one. The window
 * asks for a page at a time rather than a row at a time because the two of them cost almost the
 * same — the body, her skin and the six tables are read once for whatever is asked for, and a
 * row adds only its own textures and geometry. See [`gallery::of`], and `budget.rs` for what
 * that claim is held to.
 */
async galleryModels(pieces: WornPiece[]) : Promise<Result<GalleryPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("gallery_models", { pieces }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A page of the set grid, each set worn whole on a body of its own.
 *
 * Ids rather than pieces, which is the one thing this does not have in common with
 * [`gallery_models`] beside it. A card in the grid is a name and a count until somebody opens
 * it, so the window has no clothes to send: what a set is wearing is read here, for the whole
 * page out of one walk of each table, rather than by opening a dozen sets one at a time. See
 * [`gallery::sets`].
 */
async gallerySets(setIds: number[]) : Promise<Result<SetGalleryPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("gallery_sets", { setIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The game's own pictures for a list of things, as PNG data URLs keyed by FileDataID.
 *
 * Whatever named them — a transmog appearance, an achievement — a picture is a texture in
 * the same storage everything else comes out of, so there is one command for all of them
 * and one cache behind it. Asked for after the rows are on screen rather than with them:
 * the ids come out of the same payload the rows were drawn from, and a list reads as a list
 * long before its textures have been decoded. Icons already decoded are answered from
 * memory, which is what makes the second set of a collection cost nothing — so this only
 * reaches the game's storage when the request holds something genuinely new.
 */
async gameIcons(iconFileDataIds: number[]) : Promise<Result<IconsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("game_icons", { iconFileDataIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What a list of appearances actually is, for a set that names them and nothing else.
 *
 * An in-game set is stored as `ItemModifiedAppearance` ids because that is all the game tells
 * the addon, so opening one is this: the same four table walks a Blizzard set costs, over the
 * ids the set names rather than the ids `TransmogSetItem` names. The answer is shaped exactly
 * like `transmog_set_items`, which is what lets the window draw one with the code it already
 * has for the other.
 *
 * Asked when a reader opens a set rather than when the list is drawn, for the reason every
 * other read of the game's tables here is deferred: a roster's worth of wardrobes is a lot of
 * walking for rows nobody has looked at.
 */
async inGameSetAppearances(appearanceIds: number[]) : Promise<Result<InGameSetAppearancesPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("in_game_set_appearances", { appearanceIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The sets the player saved in the game itself, per character the addon has read one on.
 *
 * The third kind of set on that screen, and the only one this app neither invented nor found
 * in the game's files: Blizzard's sets are a DB2 table, the reader's own are rows this app
 * wrote, and these were saved at a transmogrifier long before Chronie existed. Read out of the
 * database rather than the install, so a machine without the game still lists them — see
 * `0018_in_game_sets.sql` for why listing is as far as that goes.
 */
async inGameSets() : Promise<Result<InGameSetsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("in_game_sets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installAddon() : Promise<Result<InstallResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_addon") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The look a list of items carries, as the three numbers a render is asked for by.
 *
 * The hop a segment needs and nothing else does. Every other view that draws an appearance
 * walked out of `ItemAppearance` to reach its rows and already holds these; a segment holds
 * item ids, because an item id is what the addon can catch at the moment the game says a
 * transmog source was learned. See [`appearances::of_items`].
 *
 * Asked when a reader clicks a row rather than when the segment is drawn — a modal listing
 * thirty sources would otherwise walk three of the game's tables to fill in pictures nobody
 * asked to see.
 */
async itemAppearances(itemIds: number[]) : Promise<Result<ItemAppearancesPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("item_appearances", { itemIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the game says about the items a window is showing.
 *
 * The same arrangement as the achievements above, and for the same reason: a segment carries
 * item ids — the transmog sources a character learned, the pieces an equipment set changed to
 * hold — and everything a player recognises an item by is in the game's own tables. What it
 * answers with is numbers rather than words; which subclass of armour is "Leather" is the
 * window's business.
 */
async itemDetails(ids: number[]) : Promise<Result<ItemDetailsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("item_details", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logRetention() : Promise<Result<Report, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_retention") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The pictures a list of places is drawn with, keyed by the name rather than the file.
 *
 * Keyed by the name because that is what the caller holds and all it holds: a segment arrives
 * from the addon under the name the client gave the place, and the tables that draw a dungeon are
 * keyed by that same localised name. So the whole errand happens here — the two tables, then the
 * textures — and the window gets back what it can put in an `<img>`.
 *
 * Most of what it is asked about is an open-world zone the game draws no picture for at all, and
 * those simply do not come back. See [`journal::icons_of`], and the same cache every other icon
 * goes through, so a second evening in the same dungeon costs the table reads and nothing else.
 */
async placeIcons(places: string[]) : Promise<Result<IconsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("place_icons", { places }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The wide banner each of a list of places is drawn across, keyed by the name rather than the
 * file.
 *
 * The same errand as [`place_icons`] one column over, and the reason it is a second command
 * rather than more of that one is what each is for: an icon goes beside every row of the
 * timeline, a banner above the one segment somebody opened. Asking for hundreds of headers to
 * draw one would decode a picture per evening on screen.
 *
 * Nothing comes back empty here. Most places are zones the game draws no art for at all, and
 * those are answered with the banner the group finder shows when it will not say which dungeon —
 * see [`journal::heroes_of`], which is where that choice is made and explained.
 */
async placeHeroes(places: string[]) : Promise<Result<IconsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("place_heroes", { places }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The portraits the Adventure Guide draws a list of bosses with, keyed by the encounter id.
 *
 * The same errand as [`place_icons`] over a different key, and an easier one: a fight arrives from
 * the addon as the `DungeonEncounterID` the client handed `ENCOUNTER_END`, which is a number the
 * game itself assigned rather than a localised name, so the join needs no massaging and lands on
 * nearly every fight the journal knows.
 *
 * A raid night is the same eight or ten bosses over and over, so this and the cache behind it are
 * what stop a modal opened twice reading the game's storage twice. See [`journal::portraits_of`].
 */
async bossPortraits(encounters: number[]) : Promise<Result<IconsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("boss_portraits", { encounters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The pictures a list of factions is drawn with, keyed by the name rather than the file.
 *
 * Keyed by the name for the same reason [`place_icons`] is: a reputation arrives from the addon
 * under the name the client gave the faction, and that name is the only thing the window holds.
 *
 * The hop behind it is four tables rather than two, and the picture is borrowed rather than the
 * faction's own — `Faction` has no icon column, so what this answers with is the icon of the
 * achievement for reaching Exalted with that faction. Most of what it is asked about comes back
 * with nothing: the modern renown factions have no such achievement. See [`reputations::icons_of`].
 */
async reputationIcons(factions: string[]) : Promise<Result<IconsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reputation_icons", { factions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What is in the history, so that a query can be written without reading the migrations.
 */
async querySchema() : Promise<Result<QuerySchema, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_schema") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answers with the release this binary was built as. Baked in at compile time by build.rs,
 * because a running app has no repository under it to ask.
 */
async release() : Promise<Release> {
    return await TAURI_INVOKE("release");
},
async resetActivities(segmentId: number) : Promise<Result<DashboardPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_activities", { segmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One query, typed by the reader, run against their own history.
 *
 * `async`, and therefore off the main thread, for a reason the other database commands do not
 * have: every one of those runs a statement this repository wrote and can vouch for, and this
 * one runs whatever somebody typed. `query::TIME_BUDGET` bounds how long that can take, but
 * ten seconds of a frozen window would still be ten seconds of a frozen window.
 */
async runQuery(sql: string, limit: number) : Promise<Result<QueryAnswer, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_query", { sql, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Says who she is from now on, and answers with what was stored.
 *
 * Nothing is drawn here: the window redraws her by asking for the bodies again, which is the
 * same errand it runs whenever what she is wearing changes. The one thing read out of the game
 * is whether the body named is one the game offers — a question only the install can answer now
 * that every playable race is on the list. What the game says about an *answer* is checked every
 * time a body is drawn rather than here, because an install can change under a settings file —
 * see [`customization::of`].
 */
async saveCharacterLook(body: number, picked: CharacterPick[]) : Promise<Result<CharacterChosen, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_character_look", { body, picked }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The two ways a saved set changes, each answering with every saved set rather than an
 * acknowledgement — the same rule the marks and the activity edits follow.
 */
async saveCustomSet(name: string, pieces: CustomSetPiece[]) : Promise<Result<CustomSetsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_custom_set", { name, pieces }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveWowPath(wowPath: string) : Promise<Result<SettingsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_wow_path", { wowPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Asks the game to save an outfit into the account's own transmog sets.
 *
 * The one write Chronie makes into a WoW account, and it is deliberately two steps: the request
 * is recorded here, and the *addon* carries it out the next time the player logs in. Nothing in
 * this app can reach a running game — see `docs/transmog-sets.md` — so what this does is write
 * the waiting requests into a source file of the addon's own and then wait to be told.
 *
 * Answering with every request rather than an acknowledgement, the same rule the marks and the
 * saved sets follow: the window draws what was stored, including the ones still waiting.
 *
 * A game folder that cannot be written to is not a failure of the *send*. The row is already
 * stored, every later install and every later send writes the file again, and telling somebody
 * their outfit was not saved when it is queued would be the wrong sentence.
 */
async sendSetToGame(name: string, icon: number | null, slots: InGameSetSlot[]) : Promise<Result<Request[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_set_to_game", { name, icon, slots }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionGap() : Promise<Result<Verdict, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_gap") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The two ways somebody changes a capture, answering with the whole dashboard for the same
 * reason the activity edits do: what ends up on screen is what was stored, never what the
 * window hoped the write did. Which matters more here than anywhere — a note that looked
 * saved and was not is a sentence somebody will not think to type again.
 */
async setCaptureNote(captureId: number, note: string) : Promise<Result<DashboardPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_capture_note", { captureId, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What Chronie does with a screenshot once it has found the file: how much of it to keep,
 * and whether the game keeps its own copy too.
 *
 * The two travel together because they are one decision about disk — the store's size and
 * the game folder's — and neither reaches the addon at all, so nothing is reinstalled. Both
 * only ever apply to the *next* ingestion; a picture already in the store stays exactly as it
 * was taken custody of, which is the honest behaviour: nothing here goes back and recompresses
 * something the player already has.
 */
async setCaptureStorage(quality: Quality, keepOriginals: boolean) : Promise<Result<SettingsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_capture_storage", { quality, keepOriginals }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Which things worth remembering take a picture of themselves.
 *
 * The list is the addon's to act on, so it only means anything once it is in the game folder
 * — which is why this reinstalls straight away rather than waiting for the next launch, the
 * same way combat logging does. Unknown names are not rejected here: `settings_module` drops
 * anything that is not a plain name on the way into the Lua, and a rule this build does not
 * have simply never fires.
 *
 * Answers with the whole of the settings, so the page repaints from what was stored rather
 * than from what the click hoped.
 */
async setCaptureTriggers(triggers: string[]) : Promise<Result<SettingsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_capture_triggers", { triggers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Turns Chronie's combat logging setting on or off.
 *
 * The addon is reinstalled straight away rather than at the next launch, because the setting
 * only reaches the game inside the addon folder — and answering with the resulting status
 * means the panel repaints from what the install now says instead of from what the click
 * hoped. The game reads addon files once, at load, so this takes effect at the next login or
 * `/reload`; the panel is what says so.
 */
async setCombatLogging(enabled: boolean) : Promise<Result<Status, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_combat_logging", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Turns the sweeper on at a given window, or off.
 *
 * `days` is `None` for off. Nothing is deleted here — the setting is recorded, and the sweep
 * happens on the next sync, immediately after the read that decides what is eligible. The
 * answer is the report again, so the panel repaints from what is now true rather than from
 * what the click hoped.
 */
async setLogRetention(days: number | null) : Promise<Result<Report, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_retention", { days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every outfit this app has asked the game for, and what became of each.
 */
async setRequests() : Promise<Result<Request[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_requests") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The three ways a mark changes, each answering with every mark rather than an
 * acknowledgement — the same rule the activity and capture edits follow, so what the browser
 * draws is what the database holds and never what the window hoped a write did.
 */
async setTransmogFavourite(kind: MarkSubjectKind, id: number, favourite: boolean) : Promise<Result<TransmogMarksPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_transmog_favourite", { kind, id, favourite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTransmogTag(kind: MarkSubjectKind, id: number, key: string, value: string | null) : Promise<Result<TransmogMarksPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_transmog_tag", { kind, id, key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settings() : Promise<Result<SettingsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncNow() : Promise<Result<SyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every appearance the game holds for one kind of place, whether or not a set names it.
 *
 * The display types come from the window rather than from the backend, because the kinds a
 * reader picks between do not divide the way the table does: an armour slot is one display
 * type and everything held in a hand is five. Asked for a kind at a time — the whole
 * wardrobe is fourteen megabytes and nobody browses fifty-five thousand rows at once.
 */
async transmogAppearances(displayTypes: number[]) : Promise<Result<WardrobePayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transmog_appearances", { displayTypes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Everything anybody has said about the game's wardrobe with their own hands.
 *
 * The one thing on the transmog screen that is not read out of the installed game: a star and
 * a set of tags, against a set or against a look. Read whole rather than per browser, because
 * it is what one person typed rather than what Blizzard shipped — see
 * `collector::transmog_marks`.
 */
async transmogMarks() : Promise<Result<TransmogMarksPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transmog_marks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What one transmog set is made of, walked out of the same files.
 *
 * The window already has the set from the grid, so only its id crosses over; everything a
 * row shows is resolved here rather than assembled from two halves.
 */
async transmogSetItems(setId: number) : Promise<Result<TransmogSetItemsPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transmog_set_items", { setId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The transmog sets the installed game knows about.
 */
async transmogSets() : Promise<Result<TransmogPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transmog_sets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateActivity(activityId: number, kind: string, metadata: Partial<{ [key in string]: ActivityValue }>) : Promise<Result<DashboardPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_activity", { activityId, kind, metadata }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The answer to the offer on screen. `false` is a first-class outcome, not a cancel.
 */
async wifiAnswerOffer(accepted: boolean) : Promise<Result<ReceiveStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wifi_answer_offer", { accepted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Chronies on this network that are waiting for a database.
 *
 * Async because it spends a second or so listening for answers, which on the main thread
 * would be a second of frozen window.
 */
async wifiDiscover() : Promise<Result<Peer[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wifi_discover") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts waiting for a database from another Chronie on this network, and stops again.
 *
 * Waiting is something a person switches on for as long as it takes, not something the app
 * does in the background: a machine that is always listening is one that can always be
 * asked to throw its history away.
 */
async wifiReceiveStart() : Promise<Result<ReceiveStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wifi_receive_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the receiving half is doing, asked for on a timer while the panel is open. Polled
 * rather than pushed because the whole of it is three fields, and a window that asks is a
 * window that cannot miss the one event that mattered.
 */
async wifiReceiveStatus() : Promise<Result<ReceiveStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wifi_receive_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async wifiReceiveStop() : Promise<Result<ReceiveStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wifi_receive_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Offers this machine's database to the Chronie at `address`, and sends it if they agree.
 *
 * Async and off the main thread for the same reason, only more so: this waits on somebody
 * walking to another computer.
 */
async wifiSend(address: string) : Promise<Result<Receipt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wifi_send", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The same character wearing a set of clothes, as a `.glb` in a data URL, or `null`.
 *
 * This is what most of a set has instead of a model: a chestpiece is textures painted into
 * the body's atlas and a few geoset switches, and neither means anything off the character.
 *
 * **A list rather than one appearance**, because two of the three subsystems behind character
 * rendering exist to arbitrate between items and neither can be asked one piece at a time: the
 * priority table decides which of two pieces owns a contested geoset group, and the draw order
 * decides which of two textures painting the same rectangle the reader ends up seeing. So the
 * window sends the outfit it wants to see and gets one body back.
 *
 * Each piece carries the three numbers the window already has for it. The slot comes across
 * beside the display id because `ItemAppearance` is what knows it and because it is what says
 * which geoset groups the display's six values drive, and now also where the piece sits in the
 * stack. The inventory type comes with it for the one thing the slot cannot say: which hand a
 * weapon is held in. `null` is the ordinary answer for an outfit this install can say nothing
 * about, and leaves the window showing the icons.
 */
async wornSet(pieces: WornPiece[]) : Promise<Result<WornSetPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("worn_set", { pieces }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccountCurrency = { id: number; name?: string | null; total: number; accountWide?: boolean | null; oldest?: number | null; characters: CurrencyHolder[] }
export type AccountFaction = { faction: string; best?: CharacterStanding | null; characters: CharacterStanding[] }
export type AccountGold = { characters: GoldHolder[]; wallets: number; warband?: number | null; warbandAt?: number | null; total: number; oldest?: number | null }
export type AccountHoldings = { currencies: AccountCurrency[]; factions: AccountFaction[]; gold?: AccountGold | null }
export type AchievementDetail = { id: number; title: string; description: string; reward: string; category: string[]; categoryId: number; points: number; iconFileDataId: number; faction: number }
export type AchievementDetailsPayload = { achievements: Partial<{ [key in string]: AchievementDetail }> }
export type AchievementEvent = { id: number; name?: string | null; at?: number | null; accountFirst?: boolean | null }
export type Activity = { id: number; kind: string; source: ActivitySource; confidence: number; metadata: Partial<{ [key in string]: ActivityValue }> }
export type ActivitySource = "inferred" | "manual"
export type ActivityValue = null | boolean | number | string
export type Alternate = { id: number; name: string; group: string; classMask: number; expansionId: number; patchIntroduced: number; reason: SameLookReason }
export type AppUpdateResult = { updated: boolean; version: string }
export type Capture = { id: number; sourceId: string; at: number; stamp?: string | null; imageState: CaptureImageState; note?: string | null; trigger?: string | null; achievementId?: number | null; byteSize?: number | null; sourceName?: string | null; uiMapId?: number | null; mapX?: number | null; mapY?: number | null }
export type CaptureImagePayload = { id: number; image: string | null; byteSize?: number | null }
export type CaptureImageState = "none" | "stored" | "missing"
export type CaptureThumbnailsPayload = { thumbnails: Partial<{ [key in string]: string }> }
export type CharacterBody = { id: number; name: string }
export type CharacterChosen = { body: number; picked: CharacterPick[] }
export type CharacterLookPayload = { bodies: CharacterBody[]; body: number; questions: CharacterQuestion[]; picked: CharacterPick[]; characters: PlayedCharacter[] }
export type CharacterModelPayload = { model: string }
export type CharacterPick = { question: number; swatch: number }
export type CharacterQuestion = { id: number; name: string; swatches: CharacterSwatch[] }
/**
 * What one character was last seen to have.
 */
export type CharacterSets = { character: string; sets: InGameSet[] }
export type CharacterStanding = { character: string; standing?: string | null; current?: number | null; max?: number | null; rank?: number | null; system?: string | null; at?: number | null }
export type CharacterSwatch = { id: number; name: string }
export type CharacterWornSetPayload = { model: string | null;
/**
 * How much of the character the body is really theirs — see [`character::Likeness`].
 *
 * A shape of its own rather than a `WornSetPayload` with a field added, because the two
 * commands are asking different questions: the wardrobe draws whoever the reader invented
 * and there is nothing to be uncertain about, and this draws somebody the app has to
 * recognise first and is frequently unable to.
 */
likeness: Likeness }
export type CollectibleEvent = { id: number; name?: string | null; at?: number | null; guid?: string | null }
export type CurrencyGain = { id: number; name: string; amount: number; at?: number | null; total?: number | null }
export type CurrencyHolder = { character: string; total: number; at?: number | null }
/**
 * One saved set, with everything it is made of.
 *
 * Whole rather than summarised, and unlike a Blizzard set — which is a card that costs four
 * table walks to open. A saved set is a dozen rows already written down, so there is nothing
 * to defer and no second command to ask for it with.
 */
export type CustomSet = { id: number; name: string;
/**
 * When it was first saved, and when it was last saved over. Seconds, as everything else
 * in this database is.
 */
createdAt: number; updatedAt: number; pieces: Piece[] }
export type CustomSetPiece = { place: string; appearanceId: number; itemId: number; name: string; displayType: number; inventoryType: number; displayInfoId: number; iconFileDataId: number; hasModel: boolean }
/**
 * Every set the reader has saved, which is the whole of what the window is given.
 *
 * All of them at once, for the reason the marks are: this is what one person made with their
 * own hands, so it is tens of rows rather than the game's several thousand sets.
 */
export type CustomSetsPayload = { sets: CustomSet[] }
export type DashboardPayload = { generatedAt?: string; knownActivityKinds?: string[]; segments?: Segment[]; holdings?: AccountHoldings }
export type EncounterEvent = { id: number; name?: string | null; at?: number | null; difficultyId?: number | null; groupSize?: number | null; success: boolean }
export type EquipsetChangeEvent = { setId: number; name: string; kind: EquipsetChangeKind; at?: number | null; items?: EquipsetSlotChange[] }
export type EquipsetChangeKind = "created" | "deleted" | "updated"
export type EquipsetSlotChange = { slot: number; itemId?: number | null; itemLevel?: number | null; itemName?: string | null; previousItemId?: number | null; previousItemLevel?: number | null; previousItemName?: string | null }
export type ExperienceGain = { gained: number; percent: number; startLevel?: number | null; endLevel?: number | null }
export type GalleryKind = "worn" | "held"
export type GalleryModel = { displayInfoId: number; kind: GalleryKind; model: string | null }
export type GalleryPayload = { models: GalleryModel[] }
/**
 * A session the combat log proves was played and the history does not contain.
 */
export type Gap = {
/**
 * The newest segment Chronie holds, in epoch seconds. Where the hole starts.
 */
recordedTo: number;
/**
 * The last line of the combat log, in epoch seconds. Where the hole ends.
 */
playedTo: number;
/**
 * The log that proved it, so a reader can go and look at the file rather than take this
 * on trust.
 */
log: string }
export type GoldHolder = { character: string; total: number; at?: number | null }
/**
 * One log that is gone, as the record of its going.
 */
export type Gone = { name: string; bytes: number; modified?: number | null; linesRead: number; retainDays: number; deletedAt: number }
export type HousingItemEvent = { id: number; name?: string | null; at?: number | null; warbandFirst?: boolean | null }
export type IconsPayload = { icons: Partial<{ [key in string]: string }> }
/**
 * One set the player saved in game.
 */
export type InGameSet = {
/**
 * The client's own id, which survives a rename and is what an edit names the set by.
 */
id: number; name: string;
/**
 * The FileDataID of the picture the game shows it under, where it names one.
 */
icon?: number | null;
/**
 * When the addon last saw this character's wardrobe *differ*, rather than when it last
 * looked — the addon only moves it when two looks disagree.
 */
observedAt?: number | null;
/**
 * What is in it, ascending by slot. Empty is ordinary: a set the player has named and not
 * yet filled is a set, and the game will list it for them.
 */
slots: Slot[] }
export type InGameSetAppearancesPayload = { appearances: TransmogAppearance[]; readCount: number; withheldCount: number }
export type InGameSetSlot = { slot: number; appearanceId: number; secondaryAppearanceId?: number | null; illusionId?: number | null }
/**
 * One character's sets, and every character the database has any for.
 */
export type InGameSetsPayload = {
/**
 * Keyed by the character the addon read them on, `Name-Realm`.
 *
 * Keyed by character even though the sets themselves belong to the account, because
 * *whether Chronie has ever looked* is a fact about a character. A character nobody has
 * played since Chronie was installed has no entry, which is the truth; folding them all
 * into one list would let the last alt to log out speak for the whole roster.
 */
characters: CharacterSets[] }
export type InstallResult = { version: string }
export type ItemAppearance = { appearanceId: number; displayInfoId: number; displayType: number; inventoryType: number }
export type ItemAppearancesPayload = { appearances: Partial<{ [key in string]: ItemAppearance }> }
export type ItemDetail = { id: number; name: string; classId: number; subclassId: number; inventoryType: number; quality: number; requiredLevel: number; allowableClass: number; iconFileDataId: number }
export type ItemDetailsPayload = { items: Partial<{ [key in string]: ItemDetail }> }
export type KeystoneRun = { level: number; mapId?: number | null; affixes?: number[]; startedAt?: number | null; completedAt?: number | null; completed: boolean; durationMs?: number | null; onTime?: boolean | null; upgrades?: number | null }
export type LevelUpEvent = { level: number; at?: number | null }
/**
 * How much of who a character is went into the body they were drawn on.
 *
 * **A portrait is worth nothing if it is somebody else's**, which is the whole reason this
 * travels beside the picture. Two of the three answers below are pictures the app can draw and
 * only one of them is the character; a pane that showed all three the same way would be
 * confidently wrong about most of a roster, and nothing on screen would say which.
 *
 * The distinction is the game's rather than this app's. `UnitRace` and `UnitSex` are readable
 * wherever a character is standing, so the *body* arrives for anybody the addon has seen log
 * in; what they are made of only enumerates at a barber's chair, so the *colouring* arrives
 * for a character somebody has had a haircut on and for nobody else. See `look.rs`, and
 * `docs/character-rendering.md` for the read off the client that settled it.
 */
export type Likeness =
/**
 * Nobody at all: the addon has never read this character's race, so there is no body to
 * draw them on and none is drawn. **Not the reader's own body**, which is what this used to
 * be — a Kul Tiran Male standing in for every night elf on the roster, with the pane
 * saying nothing about it.
 */
"nobody" |
/**
 * The body their race and sex name, at the swatches the game itself opens on. The clothes
 * are theirs and the shape is theirs; the skin, the hair and the face are the game's
 * defaults rather than the ones the player chose.
 */
"race" |
/**
 * Their own colouring as well, off a character the addon caught in a barber's chair.
 */
"themselves"
/**
 * The newest combat log found, as the window describes it to a reader.
 */
export type LogFile = { name: string; bytes: number;
/**
 * Epoch seconds, or `None` on a filesystem that will not say.
 */
modified?: number | null }
export type MarkSubjectKind = "set" | "appearance" | "custom"
/**
 * What a sender says about the database it is offering, before sending any of it.
 */
export type Offer = { protocol: number;
/**
 * The sending machine, as it calls itself.
 */
device: string; segmentCount: number; characterCount: number; newestDay?: string | null; bytes: number }
/**
 * The last thing that happened, kept after the connection has gone so the window can say so.
 */
export type Outcome = { stored: boolean; message: string }
/**
 * A machine found waiting, as the window lists it.
 */
export type Peer = { device: string;
/**
 * `host:port`, which is also what a person may type in by hand.
 */
address: string }
export type PetEvent = { id: number; name?: string | null; at?: number | null; guid?: string | null; speciesFirst?: boolean | null }
/**
 * One piece of a saved outfit: where it goes, and everything needed to draw it again.
 *
 * The same numbers the row it was picked from carried. `display_info_id` is the one the
 * character is actually drawn from, `appearance_id` is the game's own unit of collection and
 * so is what a mark against this piece is keyed by, and the rest is what a list draws.
 */
export type Piece = {
/**
 * Where on the body it sits, in the window's own words: `armour-3`, `hand-right`.
 *
 * Opaque here on purpose. Which hand holds a one-hander is a question the game's display
 * types cannot answer and `outfit.ts` settles for the whole view; this stores the answer.
 */
place: string; appearanceId: number; itemId: number;
/**
 * What the row was called, which is the name of the item the look was named after.
 */
name: string; displayType: number; inventoryType: number; displayInfoId: number; iconFileDataId: number; hasModel: boolean }
/**
 * A group of logs, as a number to weigh and a few names to check it against.
 */
export type Pile = { count: number; bytes: number;
/**
 * The first [`SHOWN`], oldest first.
 */
files: LogFile[] }
export type PlayedCharacter = { character: string; body: number; picked: CharacterPick[] }
/**
 * How much of a screenshot Chronie keeps once it has taken custody of it.
 *
 * The game writes a 4K PNG on a lot of installs, which is ten megabytes of a corridor. A
 * player who photographs an evening's worth of achievements every week is handing Chronie a
 * folder that only ever grows, and the pictures are looked at in a grid and in a modal — not
 * printed. So the default is a re-encode rather than the file itself, and `Original` is there
 * for somebody who disagrees, because "keep exactly what the game wrote" is a legitimate
 * thing to want and is what every install did before this setting existed.
 *
 * Named rather than numbered: a quality slider is a number nobody can predict the effect of,
 * and each of these says what it does to a screenshot in one sentence.
 */
export type Quality =
/**
 * The file the game wrote, byte for byte. The only setting that keeps a PNG a PNG.
 */
"original" |
/**
 * Every pixel, re-encoded. A 4K screenshot stays 4K and loses most of its bytes.
 */
"high" |
/**
 * Fits a retina display, which is what these are looked at on.
 */
"balanced" |
/**
 * Fits a laptop screen. For somebody keeping years of them.
 */
"small"
export type QueryAnswer = { columns: string[]; rows: QueryCell[][]; truncated: boolean; elapsedMs: number }
export type QueryCell = null | number | string
export type QueryColumn = { name: string; kind: string; primaryKey: boolean }
export type QuerySchema = { tables: QueryTable[] }
export type QueryTable = { name: string; view: boolean; rowCount?: number | null; columns: QueryColumn[] }
export type QuestEvent = { id: number; name?: string | null; at?: number | null; characterFirst?: boolean | null; accountFirst?: boolean | null }
/**
 * What became of the bytes, told to the sender so it can report something better than
 * "sent".
 */
export type Receipt = { stored: boolean; reason: string; segmentCount: number }
/**
 * Everything the window draws the receiving half from, answered whole on every poll.
 */
export type ReceiveStatus = { listening: boolean;
/**
 * This machine, as a sender will see it named.
 */
device: string;
/**
 * Where a sender can reach it, for the case where the broadcast does not arrive.
 */
addresses: string[];
/**
 * The port it actually got, which is Chronie's own unless something else held it.
 */
port: number; offer?: Waiting | null; outcome?: Outcome | null }
/**
 * Which build of Chronie this is: the channel it was published under and the commit behind it.
 *
 * There is no version number worth showing — `tauri.conf.json` carries a `0.1.<run number>` that
 * exists so the updater can compare two builds, and it says nothing to a person about what is in
 * front of them. The commit does, and it is also the only one of the two that can be looked up
 * afterwards, which is why both halves end up as links on screen. The whole forty characters
 * travel; how much of them a reader is shown is the window's business.
 */
export type Release = { channel: string; commit: string }
/**
 * Everything the retention section of Setup draws itself from.
 *
 * The preview is computed whether or not the sweeper is on, because the question somebody has
 * to answer before turning it on is "what would this delete", and the only useful answer names
 * the files. That is the dry run: it is on screen before the switch, not after the first sweep.
 */
export type Report = {
/**
 * Whether the sweeper is actually running. Off until somebody turns it on: the first sweep
 * on a machine that has been logging for a year would take the year with it, and that is
 * not a thing to do to somebody who has not been asked.
 */
enabled: boolean;
/**
 * The window in days — the one in force when `enabled`, and the one the preview below was
 * computed at when not.
 */
days: number;
/**
 * What a sweep run right now would delete.
 */
doomed: Pile;
/**
 * Old logs nothing has ever read. Never deleted, always shown: these are somebody's to
 * decide about, and a tool that hid them would be deciding for them.
 */
unread: Pile;
/**
 * Old logs a read has started and not finished. Transient — a sync or two more and they
 * move to `doomed` by themselves.
 */
unfinished: Pile;
/**
 * What sweeps have actually removed, newest first.
 */
removed: Gone[] }
export type ReputationGain = { faction: string; amount: number; at?: number | null; standing?: string | null; current?: number | null; max?: number | null }
/**
 * An outfit this app has asked the game to hold on to.
 *
 * The shape of a row of `transmog_set_requests` and its slots, and also the shape written into
 * the addon's own folder — one idea of what a send is, rather than one per hop.
 */
export type Request = { id: number; name: string; icon?: number | null; createdAt: number;
/**
 * What the addon did about it, once it has: `created`, `updated`, `full`, `refused` or
 * `failed`. Absent while the request is still waiting to be seen, which is the state the
 * window draws differently and the state that keeps it being written into the game.
 */
outcome?: string | null; appliedAt?: number | null;
/**
 * The client's id for the set that resulted, where one did.
 */
setId?: number | null; slots: Slot[] }
export type SameLookReason = "faction" | "class" | "reissue"
export type Segment = { segmentId: number; id: string; character: string; classFile?: string | null; level?: number | null; day: string; instance: string; difficulty: string; instanceType: string; difficultyId?: number | null; startedAt: number; endedAt: number; seconds: number; lootValue: number; goldDiff: number; currencyTotal?: number | null; reputationTotal?: number | null; housingXP: number; expansionTier?: number | null; latestExpansionTier?: number | null; experience?: ExperienceGain | null; keystone?: KeystoneRun | null; activities?: Activity[]; captures?: Capture[]; encounters?: EncounterEvent[]; equipsetChanges?: EquipsetChangeEvent[]; transmogs?: TransmogEvent[]; currencies?: CurrencyGain[]; reputation?: ReputationGain[]; achievements?: AchievementEvent[]; levelUps?: LevelUpEvent[]; mounts?: CollectibleEvent[]; pets?: PetEvent[]; quests?: QuestEvent[]; toys?: CollectibleEvent[]; housingItems?: HousingItemEvent[]; housingLevelUps?: LevelUpEvent[] }
export type SetGalleryModel = { setId: number; model: string | null }
export type SetGalleryPayload = { models: SetGalleryModel[] }
export type SettingsPayload = { wowPath?: string | null; lastSync?: string | null; combatLogging?: boolean; retainLogDays?: number | null; keepOriginalScreenshots?: boolean; captureQuality?: Quality; captureTriggers?: string[]; characterLook?: CharacterPick[]; characterBody?: number }
/**
 * One appearance in a set, and where on the character it sits.
 *
 * `secondary` and `illusion` are absent far more often than they are present — a slot has a
 * second appearance or an enchant illusion only if it is the kind of slot that can — and the
 * addon drops the `0` the client reports for "none", so absent here means nobody claimed
 * anything rather than "claimed to be zero".
 */
export type Slot = { slot: number;
/**
 * An `ItemModifiedAppearance` id — the same number a piece of a set saved in this app
 * carries, which is what lets the two be drawn by one piece of code.
 */
appearanceId: number; secondaryAppearanceId?: number | null; illusionId?: number | null }
/**
 * Which of the four things is true of this install.
 */
export type State =
/**
 * Chronie is not asking for logging, which is the default and costs nothing.
 */
"off" |
/**
 * Logging was asked for, but advanced logging is not confirmed on — so whatever is being
 * written has no positions in it.
 */
"basic" |
/**
 * Asked for, advanced confirmed, and a log that is actually growing.
 */
"advanced" |
/**
 * Asked for and advanced confirmed, but nothing has been written lately. Expected while
 * the game is closed; a problem if it has been days and the player has been raiding.
 */
"stale"
/**
 * Everything the Setup panel draws its combat-logging section from.
 */
export type Status = {
/**
 * Whether Chronie's own setting is on. Everything else is about what the game is doing.
 */
requested: boolean;
/**
 * The CVar as the game's config last recorded it. `None` means no config could be read
 * at all, which is not the same as off and is never reported as if it were.
 */
advanced?: boolean | null;
/**
 * Which file that answer came from, relative to the game folder, so a reader can go and
 * look. `None` when nothing was found to read.
 */
source?: string | null;
/**
 * The newest file in `Logs/` that looks like a combat log.
 */
log?: LogFile | null;
/**
 * Whether that file is actually being written: it grew since the last look, or it is
 * new, or it was touched inside the last hour.
 */
growing: boolean; state: State }
export type SyncResult = { added: number; updated: number; segmentCount: number }
export type TransmogAppearance = { modifiedAppearanceId: number; itemId: number; name: string; appearanceId: number; displayType: number; inventoryType: number; allowableClass: number; requiredLevel: number; quality: number; displayInfoId: number; iconFileDataId: number; hasModel: boolean }
export type TransmogEvent = { id: number; name?: string | null; sourceID?: number | null; appearanceID?: number | null; at?: number | null; newAppearance?: boolean | null }
export type TransmogMark = { kind: MarkSubjectKind; id: number; favourite: boolean; tags: TransmogTag[] }
export type TransmogMarksPayload = { marks: TransmogMark[] }
export type TransmogPayload = { sets: TransmogSet[]; readCount: number; declaredCount: number; withheldCount: number }
export type TransmogSet = { id: number; name: string; group: string; groupId: number; classMask: number; expansionId: number; parentId: number; flags: number; uiOrder: number; patchIntroduced: number; itemCount: number; alternates?: Alternate[] | null; sameLookAs?: number | null }
export type TransmogSetItemsPayload = { setId: number; appearances: TransmogAppearance[]; readCount: number; withheldCount: number }
export type TransmogTag = { key: string; value: string | null }
/**
 * What can be said about whether the history is complete.
 */
export type Verdict =
/**
 * Nothing was comparable, so nothing is claimed. No combat log, no readable line in the
 * one there is, or no segments to hold it against. Kept apart from [`Verdict::Complete`]
 * on purpose: "there is no hole" and "nobody looked" are not the same sentence, and a
 * window that draws them the same way is lying about the second one.
 */
{ kind: "unknown" } |
/**
 * The client was writing to its log recently enough that it may still be running. Nothing
 * is missing until a session has ended, and a session that has not ended cannot have been
 * lost.
 */
{ kind: "live" } |
/**
 * Everything the combat log proves was played is in the history.
 */
{ kind: "complete" } |
/**
 * Play the history does not contain.
 */
{ kind: "missing"; gap: Gap }
/**
 * An offer sitting on this machine's screen, waiting for somebody to answer it.
 */
export type Waiting = { offer: Offer;
/**
 * The address it arrived from, which is the only thing tying the name to a machine.
 */
from: string;
/**
 * True once it has been accepted and the bytes are on their way.
 */
receiving: boolean }
export type WardrobeAppearance = { appearanceId: number; itemId: number; name: string; displayType: number; inventoryType: number; classId: number; subclassId: number; allowableClass: number; requiredLevel: number; quality: number; displayInfoId: number; iconFileDataId: number; hasModel: boolean; itemCount: number; liftsRestriction: boolean }
export type WardrobePayload = { displayTypes: number[]; appearances: WardrobeAppearance[]; readCount: number; withheldCount: number }
export type WornPiece = { displayInfoId: number; displayType: number; inventoryType: number }
export type WornSetPayload = { model: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
