/**
 * The committed store itself, held to the shape the window reads it in.
 *
 * A contract test rather than a unit one, and it is the only test in the suite that opens
 * `data/qualities/`. What it is guarding is a seam nothing else covers: those files are written
 * by `qualities.rs` in Rust and read by `qualities.ts` in TypeScript, and the two agree by
 * convention. A column renamed on one side of that seam type-checks perfectly on the other and
 * shows up as a wardrobe with no colours on it.
 *
 * So this asserts on the artefact — that every slot is there, that a row says what a `Quality`
 * says, and that `loadQualities` actually reaches one. It deliberately asserts nothing about
 * *which* colours are in it: those are a measurement of one build of a game that gets
 * regenerated, and a test that pinned them would be a test that fails every patch for no fault.
 */

import { describe, expect, it } from "vitest";

import { colourName, indexQualities, loadQualities, loadSetQualities } from "./qualities";
import type { Quality } from "./types";

/** Every display type the game files an appearance under, which is what the store covers. */
const SLOTS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];

/** The three words `qualities::BANDS` writes, and the two ways `qualities::By` measures. */
const BANDS = ["small", "medium", "large"];
const MEASURES = ["geometry", "cover"];

const HEX = /^#[0-9a-f]{6}$/;

const rowsOf = (quality: Quality[]): Quality[] => quality;

describe("the committed store", () => {
  it.each(SLOTS)("holds a file for display type %i", async (slot) => {
    const file = await loadQualities(slot);
    expect(file).not.toBeNull();
    expect(file?.displayType).toBe(slot);
    // Which build somebody measured, which is the one thing a stored measurement must say.
    expect(file?.build).toMatch(/^\d+\.\d+\.\d+\.\d+$/);
  });

  it.each(SLOTS)("writes display type %i as rows a Quality reads", async (slot) => {
    const rows = rowsOf((await loadQualities(slot))?.appearances ?? []);
    for (const row of rows) {
      expect(Number.isInteger(row.id) && row.id > 0).toBe(true);
      expect(row.primary).toMatch(HEX);
      if (row.accent !== undefined) expect(row.accent).toMatch(HEX);
      if (row.size !== undefined) expect(BANDS).toContain(row.size);
    }
  });

  // Sorted and unique is what makes the file diffable, which is the whole reason it is
  // committed as text rather than as something smaller.
  it.each(SLOTS)("keys display type %i by appearance, ascending and once each", async (slot) => {
    const ids = (await loadQualities(slot))?.appearances.map((row) => row.id) ?? [];
    expect(ids).toEqual([...ids].sort((left, right) => left - right));
    expect(new Set(ids).size).toBe(ids.length);
  });

  it.each(SLOTS)("says what display type %i's size words were read against", async (slot) => {
    const cuts = (await loadQualities(slot))?.sizeCuts ?? {};
    for (const [by, cut] of Object.entries(cuts)) {
      expect(MEASURES).toContain(by);
      expect(cut.small).toBeLessThanOrEqual(cut.large);
      expect(cut.rows).toBeGreaterThan(0);
    }
  });

  it("holds the sets, which have colours and no size", async () => {
    const file = await loadSetQualities();
    expect(file?.sets.length).toBeGreaterThan(0);
    for (const row of file?.sets ?? []) {
      expect(row.primary).toMatch(HEX);
      // A set is a body's worth of clothes whatever is in it, so there is nothing to say.
      expect(row.size).toBeUndefined();
    }
  });

  // The seam the rest of this file is about, walked end to end once: a real file, through the
  // real loader, into the index a browser asks, and out as a word a reader would type.
  it("reads a real slot through the loader a browser uses", async () => {
    const index = indexQualities(await loadQualities(0));
    expect(index.count).toBeGreaterThan(1000);

    const first = (await loadQualities(0))?.appearances[0];
    expect(index.of(first?.id ?? 0)).toEqual(first);
    expect(colourName(first?.primary ?? "")).not.toBe("");
  });

  // A slot the store holds nothing for is an ordinary answer rather than a throw: the store is
  // regenerated by hand and the game gains display types faster than anybody runs the tool.
  it("says nothing about a display type it has no file for", async () => {
    await expect(loadQualities(99)).resolves.toBeNull();
  });
});
